version: '3.4'

services:
  ironpdfdockerclient:
    image: ${DOCKER_REGISTRY-}ironpdfdockerclient
    build:
      context: .
      dockerfile: IronPdfDockerClient/Dockerfile

  ironpdfdockerwebapi:
    image: ${DOCKER_REGISTRY-}ironpdfdockerwebapi    
    build:
      context: .
      dockerfile: IronPdfDockerWebApi/Dockerfile
    ports:
        - 6008:80
    volumes:
        - /tmp/iron:/tmp
    environment:
      LD_DEBUG: 'none'
      TESTING: 'yes'

